### ISSUE TITLE
Chatot Spawns MMO

### ISSUE THREAD

**Issue by Snoverfield** [capitalism-sudo/pla-multi-checker#8]
I don't see an option for 7 on first wave from Chatot massive mass outbreak. I had 7 from first group and 6 from next group. I tried running the seed with 8 selected and being as non hostile I got lucky and landed a [1,1,1,1]+Revisit[3,1] which required no multi battles. But did not get the shiny where it said. Probably cause it initially had 7 spawn not 8.

**Comment by capitalism-sudo** [comment]
7 is not a possible spawn. It is 4 + number of respawns.
